name: "Open WebUI"
description: "Open WebUI is an extensible, feature-rich, and user-friendly self-hosted AI platform designed to operate entirely offline"
url: https://github.com/mikastamm/open-webui-homeassistant-addon
version: "v0.7.3"
slug: "openwebui-custom"
panel_icon: mdi:message
init: false

build_from:
  aarch64: ghcr.io/open-webui/open-webui:main
  amd64: ghcr.io/open-webui/open-webui:main

arch:
  - aarch64
  - amd64
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:8080]"
host_network: true
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "Open WebUI Web Interface"
map:
  - share
environment:
  JWT_EXPIRES_IN: "5m"
options: {}
schema: {}
