name: "Open WebUI Custom"
description: "Open WebUI with custom JWT timeout"
url: https://github.com/ovenlade/hassio-addons
version: "v0.7.6"
slug: "openwebui-custom"
panel_icon: mdi:message
init: false

arch:
  - aarch64
  - amd64

startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:8080]"
ports:
  8080/tcp: 8080
map:
  - share
environment:
  JWT_EXPIRES_IN: "5m"
options: {}
schema: {}
